theme: jekyll-theme-slate
title: Mark Parayil's Datacentric Portfolio!
description: This page provides summaries and source code to the projects that I've completed in my career as a Data Engineer & professional.
