theme: jekyll-theme-slate
title: Mark Parayil's Datacentric Portfolio!
description: This landing page provides an deep dives on projects that I've workd on as a Data Engineer & Analytical Professional.
