theme: jekyll-theme-slate
title: Mark Parayil's data projects and applications Portfolio!
description: This page provides summaries and source code to the projects that I've completed in my career as a Data professional & developer.
