theme: jekyll-theme-slate
title: You've landed on Mark Parayil's portfolio of data projects and applications!
description: This page provides summaries and source code to the projects that I've completed in my career as a Data professional & developer.
